# coding: utf-8

"""
    DevCycle Bucketing API

    Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import devcycle_python_sdk
from devcycle_python_sdk.models.variable import Variable  # noqa: E501
from devcycle_python_sdk.rest import ApiException


class TestVariable(unittest.TestCase):
    """Variable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariable(self):
        """Test Variable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = devcycle_python_sdk.models.variable.Variable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
