# coding: utf-8

"""
    DevCycle Bucketing API

    Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest



class TestUserData(unittest.TestCase):
    """UserData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserData(self):
        """Test UserData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = devcycle_python_sdk.models.user_data.UserData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
