version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "devcyclehq/engineering"
    versioning-strategy: increase
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "devcyclehq/engineering"
