# https://beta.ruff.rs/docs/rules/
select = [
	"F", # PyFlakes
	"E", # pycodestyle error
	"W", # pycodestyle warning
	"N", # pep8-naming
	"T20", # flake8-print
	"RUF100", # ensure noqa comments actually match an error
]
ignore = [
	"E501", # line too long
]
exclude = [
  "variableForUserParams_pb2.pyi"
]
[per-file-ignores]
"__init__.py" = ["F401"]
"variableForUserParams_pb2.py" = ["F821", "N999", "E712"]

