# pytest options
[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--benchmark-skip --showlocals"

# black options
[tool.black]
target-version = ['py39']
extend-exclude = '_pb2\.pyi?$'

# mypy options
[tool.mypy]
python_version = "3.9"
exclude = "django-app"

# See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
# To silence errors from within a 3rd party package, use ignore_errors
# To silence "Skipping analyzing X: module is installed, but missing library stubs or py.typed marker" use ignore_missing_imports
[[tool.mypy.overrides]]
module = 'devcycle_python_sdk.protobuf.*'
ignore_errors = true

[[tool.mypy.overrides]]
module = 'setuptools'
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = 'test.openfeature.*'
ignore_errors = true

[[tool.mypy.overrides]]
module = 'ld_eventsource.*'
ignore_errors = true
ignore_missing_imports = true


[[tool.mypy.overrides]]
module = 'openfeature.*'
ignore_errors = true
ignore_missing_imports = true

# ruff options
[tool.ruff]
# https://beta.ruff.rs/docs/rules/
select = [
	"F",      # PyFlakes
	"E",      # pycodestyle error
	"W",      # pycodestyle warning
	"N",      # pep8-naming
	"T20",    # flake8-print
	"RUF100", # ensure noqa comments actually match an error
]
ignore = [
	"E501", # line too long
]
exclude = ["variableForUserParams_pb2.pyi"]
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"variableForUserParams_pb2.py" = ["F821", "N999", "E712"]
