# coding: utf-8

"""
    DevCycle Bucketing API

    Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301
import os

NAME = "devcycle-python-server-sdk"
version_file = open(os.path.join('devcycle_python_sdk', 'VERSION.txt'))
VERSION = version_file.read().strip()
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="DevCycle Bucketing API",
    author_email="",
    url="https://github.com/devcycleHQ/python-server-sdk",
    download_url="https://github.com/taplytics/devcycle-python-sdk/archive/refs/tags/0.0.0-alpha-1.tar.gz",
    keywords=["DevCycle"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.  # noqa: E501
    """
)
