# coding: utf-8

"""
    DevCycle Bucketing API

    Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserDataAndEventsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'events': 'list[Event]',
        'user': 'UserData'
    }

    attribute_map = {
        'events': 'events',
        'user': 'user'
    }

    def __init__(self, events=None, user=None):  # noqa: E501
        """UserDataAndEventsBody - a model defined in Swagger"""  # noqa: E501
        self._events = None
        self._user = None
        self.discriminator = None
        if events is not None:
            self.events = events
        if user is not None:
            self.user = user

    @property
    def events(self):
        """Gets the events of this UserDataAndEventsBody.  # noqa: E501


        :return: The events of this UserDataAndEventsBody.  # noqa: E501
        :rtype: list[Event]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this UserDataAndEventsBody.


        :param events: The events of this UserDataAndEventsBody.  # noqa: E501
        :type: list[Event]
        """

        self._events = events

    @property
    def user(self):
        """Gets the user of this UserDataAndEventsBody.  # noqa: E501


        :return: The user of this UserDataAndEventsBody.  # noqa: E501
        :rtype: UserData
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserDataAndEventsBody.


        :param user: The user of this UserDataAndEventsBody.  # noqa: E501
        :type: UserData
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserDataAndEventsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserDataAndEventsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
