# coding: utf-8

"""
    DevCycle Bucketing API

    Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Variable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'key': 'str',
        'type': 'str',
        'is_defaulted': 'bool',
        'value': 'object'
    }

    attribute_map = {
        'id': '_id',
        'key': 'key',
        'type': 'type',
        'is_defaulted': 'is_defaulted',
        'value': 'value'
    }

    def __init__(self, id=None, key=None, type=None, value=None, is_defaulted=False):  # noqa: E501
        """Variable - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._key = None
        self._type = None
        self._value = None
        self._is_defaulted = False
        self.discriminator = None
        self.id = id
        self.key = key
        self.type = type
        self.value = value
        self.is_defaulted = is_defaulted

    @property
    def id(self):
        """Gets the id of this Variable.  # noqa: E501

        unique database id  # noqa: E501

        :return: The id of this Variable.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Variable.

        unique database id  # noqa: E501

        :param id: The id of this Variable.  # noqa: E501
        :type: str
        """

        self._id = id
    @property
    def is_defaulted(self):
        """Gets the is_defaulted of this Variable.  # noqa: E501

        identifies whether variable value came from server or given default # noqa: E501

        :return: The is_defaulted of this Variable.  # noqa: E501
        :rtype: bool
        """
        return self._is_defaulted

    @is_defaulted.setter
    def is_defaulted(self, is_defaulted=False):
        """Sets the is_defaulted of this Variable.

        identifies whether variable value came from server or given default # noqa: E501

        :param is_defaulted: The is_defaulted of this Variable.  # noqa: E501
        :type: str
        """

        self._is_defaulted = is_defaulted
    @property
    def key(self):
        """Gets the key of this Variable.  # noqa: E501

        Unique key by Project, can be used in the SDK / API to reference by 'key' rather than _id.  # noqa: E501

        :return: The key of this Variable.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this Variable.

        Unique key by Project, can be used in the SDK / API to reference by 'key' rather than _id.  # noqa: E501

        :param key: The key of this Variable.  # noqa: E501
        :type: str
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def type(self):
        """Gets the type of this Variable.  # noqa: E501

        Variable type  # noqa: E501

        :return: The type of this Variable.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Variable.

        Variable type  # noqa: E501

        :param type: The type of this Variable.  # noqa: E501
        :type: str
        """
        if type is None:
            self._type = None
            return
        allowed_values = ["String", "Boolean", "Number", "JSON"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def value(self):
        """Gets the value of this Variable.  # noqa: E501

        Variable value can be a string, number, boolean, or JSON  # noqa: E501

        :return: The value of this Variable.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Variable.

        Variable value can be a string, number, boolean, or JSON  # noqa: E501

        :param value: The value of this Variable.  # noqa: E501
        :type: object
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Variable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Variable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
