name: Lint
on: pull_request

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: chartboost/ruff-action@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.test.txt

      - name: Check formatting
        run: |
          black --check .

      - name: Run mypy
        run: |
          mypy .