name: Test Examples

on: [push]

permissions:
  contents: read

jobs:
  test_examples:
    name: Test Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
      - name: Run local bucketing example
        run: |
          cd example && python local_bucketing_client_example.py
        env:
          DEVCYCLE_SERVER_SDK_KEY: dvc_server_token_hash
      - name: Run cloud bucketing example
        run: |
          cd example && python cloud_client_example.py
        env:
          DEVCYCLE_SERVER_SDK_KEY: dvc_server_token_hash
      - name: Run OpenFeature example
        run: |
          cd example && python openfeature_example.py
        env:
          DEVCYCLE_SERVER_SDK_KEY: dvc_server_token_hash
